apiVersion: apps/v1
kind: Secret
metadata:
    name: {{ include "deconz.fullname" . }}-env
    labels:
        {{- include "deconz.labels" . | nindent 4 }}
data:
    {{- if .Values.deconz.vnc.enabled }}
    {{- if not .Values.deconz.vnc.passwordInFile }}
    DECONZ_VNC_PASSWORD: {{ .Values.deconz.vnc.password }} 
    {{- else }}
    DECONZ_VNC_PASSWORD_FILE: {{ .Values.deconz.vnc.passwordInFile.passwordFile }}
    {{- end }}
    {{- end }}