apiVersion: v1
kind: Service
metadata:
  name: {{ include "deconz.fullname" . }}-web
  labels:
    {{- include "deconz.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.deconz.webPort }}
      targetPort: {{ .Values.deconz.webPort }}
      protocol: TCP
      name: webPort
  selector:
    {{- include "deconz.selectorLabels" . | nindent 4 }}
