apiVersion: v1
kind: Service
metadata:
  name: {{ include "deconz.fullname" . }}-nodeports
  labels:
    {{- include "deconz.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.deconz.wsPort }}
      targetPort: {{ .Values.deconz.wsPort }}
      protocol: TCP
      name: wsPort
    {{- if .Values.deconz.vnc.enabled  -}}
    - port: {{ .Values.deconz.vnc.port }}
      targetPort: {{ .Values.deconz.vnc.port }}
      protocol: TCP
      name: vncPort
    {{- end -}}
    {{- if .Values.deconz.novnc.enabled  -}}
    - port: {{ .Values.deconz.novnc.port }}
      targetPort: {{ .Values.deconz.novnc.port }}
      protocol: TCP
      name: novncPort
    {{- end -}}
  selector:
    {{- include "deconz.selectorLabels" . | nindent 4 }}
