name: Monitor image for version changes for upstream

on:
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:
    
    
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Check image upstreams for changes in master
      id: version
      run: |   
        DECONZ_APPVERSION=$(curl -s https://raw.githubusercontent.com/deconz-community/deconz-docker/main/version.json | grep 'version' | head -n1 | awk '{print $2;}' | sed 's/[",]/''/g')
        if [[ -z ./.github/deconz_version ||  $DECONZ_APPVERSION -ne $(cat ./.github/deconz_version) ]]; then
          echo "deconz_changed=true" >> $GITHUB_ENV; echo "version_change=true" >> $GITHUB_ENV; echo $DECONZ_APPVERSION >> ./.github/deconz_version; else echo "deconz_changed=false" >> $GITHUB_ENV; fi
        OPENHAB_HEAD=$(git ls-remote https://github.com/openhab/openhab-docker refs/heads/main | head -n1 |awk '{print $1;}')
        if [[ -z ./.github/openhab_version ]] || $OPENHAB_HEAD -ne $(cat ./.github/openhab_head); then
          echo "openhab_changed=true" >> $GITHUB_ENV; echo "version_change=true" >> $GITHUB_ENV; echo $OPENHAB_HEAD >> ./.github/openhab_head; else echo "openhab_changed=false" >> $GITHUB_ENV; fi
        fi
    
    - name: Update deCONZ appVersion
      if: ${{ github.deconz_changed == 'true'}}
      run: |
        sed -i "s/^appVersion:.*/appVersion: $DECONZ_APPVERSION/" ./charts/deconz/Chart.yaml
    
    - name: Update OpenHAB appVersion
      if: ${{ github.openhab_changed == 'true'}}
      run: |
        sed -i "s/^appVersion:.*/appVersion: $OPENHAB_APPVERSION/" ./charts/openhab/Chart.yaml

    - name: Commit changes
      id: commit
      if: ${{ github.version_change == 'true' }}
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"
        git commit -m "Updating appVersion(s)" -a
        if [ -z "$(git status --porcelain)" ]; then
          echo "Nothing changed"
          echo "push=false" >> $GITHUB_ENV
        else
          echo "Committing upstream commit hash"
          echo "push=true" >> $GITHUB_ENV
        fi
      shell: bash
    
    - name: Push changes
      if: ${{ github.push == 'true' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}