name: Monitor image for version changes for upstream

on:
  push:
    branches:
      - master
      - develop
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:
    
    
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Check image upstreams for changes in master
      id: version
      run: |   
        DECONZ_APPVERSION=$(curl -s https://raw.githubusercontent.com/deconz-community/deconz-docker/main/version.json | grep 'version' | head -n1 | awk '{print $2;}' | sed 's/[",]//g')
        echo deCONZ version is $DECONZ_APPVERSION.
        if [[ -z $(cat ./.github/deconz_version) ||  $DECONZ_APPVERSION != $(cat ./.github/deconz_version) ]]; then
            echo "DeCONZ has changed, previous version was $(cat ./.github/deconz_version)"
            echo "deconz_changed=true" >> $GITHUB_ENV
            echo "version_change=true" >> $GITHUB_ENV
            echo "$DECONZ_APPVERSION" > ./.github/deconz_version;
        else 
            echo "deconz_changed=false" >> $GITHUB_ENV;
            echo "DeCONZ has not changed, still at $(cat ./.github/deconz_version)"
        fi
        OPENHAB_HEAD=$(git ls-remote https://github.com/openhab/openhab-docker refs/heads/main | head -n1 |awk '{print $1;}')
        echo OpenHAB head commit is $OPENHAB_HEAD.
        if [[ -z $(cat ./.github/openhab_head) || $OPENHAB_HEAD != "$(cat ./.github/openhab_head)" ]]; then
            echo "OpenHAB has changed, previous one was $(cat ./.github/openhab_head)"
            echo "openhab_changed=true" >> $GITHUB_ENV
            echo "version_change=true" >> $GITHUB_ENV
            echo "$OPENHAB_HEAD" > ./.github/openhab_head;
        else
            echo "openhab_changed=false" >> $GITHUB_ENV;
            echo "OpenHAB has not changed, still at $(cat ./.github/openhab_head)"

        fi
        echo  "DeCONZ changed: ${{ env.deconz_changed }}";
        echo "OpenHAB changed: ${{ env.openhab_changed }}";
        echo "Version change: ${{ env.version_change }}";
    
    - name: Update deCONZ appVersion
      if: ${{ env.deconz_changed == 'true'}}
      run: |
        sed -i "s/^appVersion:.*/appVersion: $DECONZ_APPVERSION/" ./charts/deconz/Chart.yaml
    
    - name: Update OpenHAB appVersion
      if: ${{ env.openhab_changed == 'true'}}
      run: |
        sed -i "s/^appVersion:.*/appVersion: $OPENHAB_APPVERSION/" ./charts/openhab/Chart.yaml

    - name: Commit changes
      id: commit
      if: ${{ env.version_change == 'true' }}
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"
        git commit -m "Updating appVersion(s)" -a
        if [ -z "$(git status --porcelain)" ]; then
          echo "Not committing"
          echo "push=false" >> $GITHUB_ENV
        else
          echo "Committing upstream changes"
          echo "push=true" >> $GITHUB_ENV
        fi
      shell: bash
    
    - name: Push changes
      if: ${{ env.push == 'true' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run DeCONZ chart-releaser
      if: ${{ env.deconz_changed == 'true' }}
      run: |
        curl \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.RELEASE_DISPATCH_TOKEN }}"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/TLii/charts/actions/workflows/deconz_release.yaml/dispatches \
        -d '{"ref":"$GITHUB_BASE_REF"}}'

    - name: Run OpenHAB chart-releaser
      if: ${{ env.openhab_changed == 'true' }}
      run: |
        curl \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.RELEASE_DISPATCH_TOKEN }}"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/TLii/charts/actions/workflows/openhab_release.yaml/dispatches \
        -d '{"ref":"$GITHUB_BASE_REF"}}'